drop table if exists bookmarks;

create table bookmarks (
    id INTEGER primary key generated by default as identity,
    title TEXT NOT NULL,
    url TEXT NOT NULL,
    description TEXT,
    rating INTEGER NOT NULL default 0
);

insert into bookmarks (title, url, description, rating)
values 
    ('News', 'www.bbc.com', 'news bookmark', 4)
    ('Sports', 'www.espn.com', 'sports bookmark', 5)
    ('Gaming', 'www.bbc.com', 'gaming bookmark', 1)
    ('Social media', 'www.weibo.com', 'social media bookmark', 3)
    ('Online trading', 'www.betterment.com', 'stocks and shares bookmark', 5)
    ('Online banking', 'www.chase.com', 'banking bookmark', 3)
    ('JS tutorial', 'www.w3schools.com', 'JS education bookmark', 5)
    ('Fake news', 'www.trump.com', 'alt news bookmark', 0)
    ('Movie rating', 'www.imdb.com', 'movie rating bookmark', 5)
    ('Search engine', 'www.lycos.com', 'failed engine bookmark', 1);
    